### PR TITLE
issues-152: Update screenshot for README

### PR DESCRIPTION
**Pull request by mpaarating**
Per #152, this PR updates the screenshot shown in the README.

I chose a green background because I think it is lovely.

[screenshot of electric io application](https://gyazo.com/c96868a43b7ae999c8a6aaafdcd532ad)

### CODE REVIEW

**Comment by kleinfreund** [comment]
This looks goot to me; I just have a small nitpick: If you would be so kind, could you make sure that there is a tiny gap between the Cool Button and the Sticker Time cards? :)

Two bordered shapes barely overlapping

The buttons closely sticking together like this makes me a bit nervous.

**Comment by mpaarating** [comment]
@kleinfreund good catch. I took the opportunity to somewhat better organize the windows compared to what I had before.

**Comment by mtheoryx** [comment]
That looks awesome to me!

**Comment by noopkat** [comment]
beautiful work, @mpaarating ! 
Thanks for the updated screenshot ✨ 

image

**Pull request merged**
