### PR TITLE
Fix broken docker build

### LINKED ISSUE #74: Docker build broken and npm package mismatch potential
**TLDR**: I already have a fix for this, but wanted to record this correctly as an issue. I'll take it asap.

## Docker node_modules are just a whole buncha messed up

This is my bad. What's happening currently is that on build-time, docker seems to be working fine. However, on run-time, where the volume mapping comes in, we end up with new-hotness from several PRs ago not being reflected. And this is not 100% reproducible, depending on whether you already had this stuff installed on your dev machine.

Fix is to correctly map app and node_modules volumes in docker-compose, in addition to copying in the package-lock.json into the container for the new build step.

## Version mismatch between VUE and vue-template-compiler

Vue was at `2.5.16` as a dependency and vue-template-compiler was added at `~2.5.16`. The latter issued a patch fix `~2.5.17` and appeared to be causing an error.

Fix is to lock down vue-template-compiler to `2.5.16` to keep in step with vue releases.

### PR DESCRIPTION
**Pull request by mtheoryx**
So... I broke the build :|

image

2 things happened.

1. I was handling volume mounts irresponsibly and got into a super weird space after some updates. And I could reproduce it (yay). That's fixed now.
2. There was a patch version update of vue-template-compiler that caused "whelp guess I'll just give up and die" from the webpack dev server. I locked that down.

It was not locked down because it's generally safe enough as a devDependency... but these things can still happen!

So, we should be good!

image

Fixes #74

### CODE REVIEW

**Comment by toolboc** [comment]
@mtheoryx , looks like I stumbled across the same issue in #78 , I fixed by adding as a regular dependency. in #79

**Comment by noopkat** [comment]
hey @mtheoryx this seems chill 👌

**Comment by toolboc** [comment]
@mtheoryx , I pulled changes locally and spun up a container instance with no issues, looks good!

**Comment by mtheoryx** [comment]
@toolboc Thank you so much for the independent verification!

image

**Pull request merged**
