### PR TITLE
fixes #54 adds debug package for firehose logging

### LINKED ISSUE #54: Environment option for debug/firehose?
Suz turned off the firehose in simulation mode, but also mentioned a debug mode possibility?

We can really easily support that with env vars.

Thoughts?

[maintainers: a good label would just be "question" or something]. Cheers!

### PR DESCRIPTION
**Pull request by noopkat**
👋 hello!

Kinda does what it says on the tin? 👀 
I decided to add the debug package because I really like the features it offers.

Thanks for the help on the stream everyone! 💖 

bitmoji

### CODE REVIEW

**Comment by mtheoryx** [comment]
Fantastic!

@noopkat one think that I know we've been kinda mentioning is documentation of the .env and potential ways to use those env vars in docker, and just the CLI.

I wouldn't want to hold this PR up, so maybe we could have a standalone issue around "clarify documentation around environment variables and the environment file?"

It would consolidate where changes happen (probably just in the readme) and also be a candidate for "good first issue".

What do you think?

**Comment by mtheoryx** [comment]
Just for clarification, I think this one is good to go!

**Comment by noopkat** [comment]
yes agreed - let's raise an issue for the docs! ✨

**Comment by mtheoryx** [comment]
New issue created #60

**Pull request merged**
