### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by atbuzz**

### CODE REVIEW

**Comment by mtheoryx** [comment]
Looks good to me!

**Comment by atbuzz** [comment]
Cheers @mtheoryx, I saw your issue.

**Comment by escherina** [comment]
Looks great to me! Thanks for the PR, @atbuzz. 👌 Will merge this in now.

**Comment by atbuzz** [comment]
Thanks @escherina, big fan by the way.

**Pull request merged**
